puppetboard

diff --git a/bootstrap/puppet-master b/bootstrap/puppet-master
--- a/bootstrap/puppet-master
+++ b/bootstrap/puppet-master
@@ -15,8 +15,8 @@ fi
 wget https://apt.puppetlabs.com/puppetlabs-release-trusty.deb
 dpkg -i puppetlabs-release-trusty.deb && rm  -f puppetlabs-release-trusty.deb
 
-wget https://apt.puppetlabs.com/puppetlabs-release-pc1-trusty.deb
-dpkg -i puppetlabs-release-pc1-trusty.deb && rm -f puppetlabs-release-pc1-trusty.deb
+#wget https://apt.puppetlabs.com/puppetlabs-release-pc1-trusty.deb
+#dpkg -i puppetlabs-release-pc1-trusty.deb && rm -f puppetlabs-release-pc1-trusty.deb
 
 if [[ $? != 0 ]];then
     echo 'install puppet  repo failed'
@@ -76,18 +76,18 @@ if [[ $? != 0 ]]; then
     exit 1
 fi
 
-#puppet apply puppetdb.pp --modulepath /etc/puppet/environments/production/modules/ 
-#if [[ $? != 0 ]]; then
-#    echo 'install puppetdb failed'
-#    exit 1
-#fi
+puppet apply puppetdb.pp --modulepath /etc/puppet/environments/production/modules/  && service apache2 restart
+if [[ $? != 0 ]]; then
+    echo 'install puppetdb failed'
+    exit 1
+fi
 
 puppet agent -t
 
-#if [[ $? != 0 ]]; then
-#    echo 'init puppet'
-#    exit 1
-#fi
+if [[ $? != 0 ]]; then
+    echo 'init puppet'
+    exit 1
+fi
 #puppet master --verbose --no-daemonize
 #if [[ $? != 0 ]];then
 #    echo "create cert failed"
